---
# tasks file for gromacs install

- name: make build directory
  file: path=/opt/gromacs state=directory

- name: download gromacs
  get_url: url={{ gromacs_url }} dest=/tmp/gromacs-{{ gromacs_version }}.tar.gz

- name: extract gromacs tarball
  unarchive: copy=no src=/tmp/gromacs-{{ gromacs_version }}.tar.gz dest=/tmp creates=/tmp/gromacs-{{ gromacs_version }}

- name: make build directory
  file: path=/tmp/gromacs-{{ gromacs_version }}/build state=directory

- name: build gromacs
  shell: CC=mpicc CXX=mpicxx cmake .. -DGMX_SIMD=AVX2_256 -DGMX_MPI=ON -DGMX_DOUBLE=ON -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DCMAKE_INSTALL_PREFIX={{ gromacs_prefix }}
  args:
    chdir: /tmp/gromacs-{{ gromacs_version }}/build
    creates: /tmp/gromacs-{{ gromacs_version }}/build/Makefile
  environment:
    PATH: "{{ gcc_prefix }}/bin:{{ binutils_prefix }}/bin:{{ openmpi_prefix }}/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"
    LD_LIBRARY_PATH: "{{ gcc_prefix }}/lib64:{{ binutils_prefix }}/lib:{{ openmpi_prefix }}/lib:{{ openmpi_prefix }}/lib/openmpi"

- name: install gromacs
  shell: make && make install
  args:
    chdir: /tmp/gromacs-{{ gromacs_version }}/build
  environment:
    PATH: "{{ gcc_prefix }}/bin:{{ binutils_prefix }}/bin:{{ openmpi_prefix }}/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"
    LD_LIBRARY_PATH: "{{ gcc_prefix }}/lib64:{{ binutils_prefix }}/lib:{{ openmpi_prefix }}/lib:{{ openmpi_prefix }}/lib/openmpi"
