---
# tasks file for gromacs

- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - cmake
    - fftw
    - fftw-devel

- name: check if already installed
  stat: path={{ gromacs_prefix }}
  register: gromacs_dir
  changed_when: gromacs_dir.stat.exists == False

- include: install.yml
  when: gromacs_dir.stat.exists == False
